---
- name: Deploy application
  hosts: app
  tasks:
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/Otus-DevOps-2017-11/reddit.git'
      dest: "/home/{{ deploy_user }}/reddit"
      version: monolith
    tags: deploy-tag
    notify: restart puma

  - name: Bundle install
    bundler:
      state: present
      chdir: "/home/{{ deploy_user }}/reddit"
    tags: deploy-tag

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
